version: '2.0'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis (nothing to do here)
  rabbitmq:
    image: rabbitmq:3-management
    ## todo: Initialize vhost??
  elasticsearch:
    image: elasticsearch:2.x.x
    ## todo: powershell to setup default indexes
    ## expose kibiana and server ports
  sqlserver-linux:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    ## todo: need link to the temp-site database here
    ## todo: run migrations upto latest code build
volumes:
  logvolume01: {}
